import { Orbitron,Train_One,Bungee_Outline } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import StairTransition from "@/components/StairTransition";
import PageTransition from "@/components/PageTransition";
import { ReactElement } from "react";

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900",],
  variable: "--font-orbitron"
});

const train_One = Train_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-train_One"
});

const bungee_Outline = Bungee_Outline ({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-Bungee_Outline"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProp {
  children : ReactElement
}

export default function RootLayout({ children } : RootLayoutProp) {
  return (
    <html lang="en">
      <body className={`${orbitron.variable} ${train_One.variable} ${bungee_Outline.variable}`}>
        
        <Header />
        <StairTransition />
        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
